# Nombre de la aplicación
spring.application.name=inmosaas-backend

# Configuración de Conexión a PostgreSQL (Docker)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/inmosaas_db}
spring.datasource.username=${DB_USERNAME:inmosaas_user}
spring.datasource.password=${DB_PASSWORD:inmosaas_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
